dist: xenial

sudo: required

language: python

python:
  - "3.8.2"


install:
  - python --version
  - pip install cloudmesh-installer
  - cloudmesh-installer get storage
  - cms help
  - ls
  - pwd

script:
  - cms set storage=local
  - pytest -v --capture=no tests/test_01_storage_size.py
  - pytest -v --capture=no tests/test_02_storage_installer.py
  - pytest -v --capture=no tests/test_03_storage_local.py
  - pytest -v --capture=no tests/test_04_storage_copy.py
